POST http://localhost:3001/api/student/ HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMGUzNzk5YzBiNDc5ODZiZjEyMjJiYSIsImVtYWlsIjoiY2FtYXJpYW5hQGdjLmVkdS5nbSIsImlhdCI6MTYyODMyMTY4OSwiZXhwIjoxNjI4MzI1Mjg5fQ.eR97e-jC5cbEMU6Ihwa8FLlmpoA-AUopYTvCnlDKd1E

{
  "likes": 100,
  "title": "Which jobs help people the most?",
  "author": "Benjamin Todd",
  "url": "https://80000hours.org/career-guide/high-impact-jobs/#approach-1-earning-to-give"
}

###
POST http://localhost:3001/signup HTTP/1.1
content-type: application/json

{
  "email": "camariana@gc.edu.gm",
  "password": "secrete"
}


###
POST http://localhost:3001/signin HTTP/1.1
content-type: application/json

{
  "email": "camariana@gc.edu.gm",
  "password": "secrete"
}