GET http://localhost:3001/api/student/610e3d3c68bc6c9113640905
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMGUzNzk5YzBiNDc5ODZiZjEyMjJiYSIsImVtYWlsIjoiY2FtYXJpYW5hQGdjLmVkdS5nbSIsImlhdCI6MTYyODMyMTY4OSwiZXhwIjoxNjI4MzI1Mjg5fQ.eR97e-jC5cbEMU6Ihwa8FLlmpoA-AUopYTvCnlDKd1E

###
GET http://localhost:3001/api/user/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMGUzNzk5YzBiNDc5ODZiZjEyMjJiYSIsImVtYWlsIjoiY2FtYXJpYW5hQGdjLmVkdS5nbSIsImlhdCI6MTYyODMyMTY4OSwiZXhwIjoxNjI4MzI1Mjg5fQ.eR97e-jC5cbEMU6Ihwa8FLlmpoA-AUopYTvCnlDKd1E
